version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.5
    expose: ["2181"]
    networks:
      - clickhouse_network
    environment:
      ZOO_AUTOPURGE_PURGEINTERVAL: 1

  clickserver1:
    image: yandex/clickhouse-server@sha256:1cbf75aabe1e2cc9f62d1d9929c318a59ae552e2700e201db985b92a9bcabc6e
    env_file: .clickhouse_env
    hostname: clickserver1
    restart: always
    networks:
      - clickhouse_network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_db1:/var/lib/clickhouse
      - clickhouse_logs1:/var/log/clickhouse-server
    configs:
      - source: zookeeper.xml
        target: /etc/clickhouse-server/config.d/zookeeper.xml
      - source: macros_replica1.xml
        target: /etc/clickhouse-server/config.d/macros.xml
      - source: cluster.xml
        target: /etc/clickhouse-server/config.d/cluster.xml
    depends_on:
      - zookeeper
    deploy:
      placement:
        constraints:
          - node.hostname == hostname1  # replace with your 1st server's hostname

  clickserver2:
    image: yandex/clickhouse-server@sha256:1cbf75aabe1e2cc9f62d1d9929c318a59ae552e2700e201db985b92a9bcabc6e
    env_file: .clickhouse_env
    restart: always
    hostname: clickserver2
    networks:
      - clickhouse_network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_db2:/var/lib/clickhouse
      - clickhouse_logs2:/var/log/clickhouse-server
    configs:
      - source: zookeeper.xml
        target: /etc/clickhouse-server/config.d/zookeeper.xml
      - source: macros_replica2.xml
        target: /etc/clickhouse-server/config.d/macros.xml
      - source: cluster.xml
        target: /etc/clickhouse-server/config.d/cluster.xml
    depends_on:
      - zookeeper
    deploy:
      placement:
        constraints:
          - node.hostname == hostname2  # replace with your 2nd server's hostname

  click_client:
    image: yandex/clickhouse-client@sha256:9ae2ee421c9c9f00406a39a1174276aa23abb7fceac13b40578b18eeaa9bc4d1
    entrypoint:
      - /bin/sleep
    restart: always
    networks:
      - clickhouse_network
    command:
      - infinity

networks:
  clickhouse_network:
    driver: overlay
configs:
  zookeeper.xml:
    external: true
  macros_replica1.xml:
    external: true
  macros_replica2.xml:
    external: true
  cluster.xml:
    external: true
volumes:
  clickhouse_db1:
    driver: local
  clickhouse_logs1:
    driver: local
  clickhouse_db2:
    driver: local
  clickhouse_logs2:
    driver: local
